### ISSUE TITLE
Code run time Error (livechat-widget' is not a known element)

### ISSUE THREAD

**Issue by AmolShinde11** [livechat/chat-widget-adapters#26]
**Describe the bug**
We try to test LiveChat on our application but it did not work, tried to run code but that time showed an error. 

We have referenced the document for implementation.
https://github.com/livechat/chat-widget-adapters

**To Reproduce**
See error:
error NG8001: 'livechat-widget' is not a known element:
    1. If 'livechat-widget' is an Angular component, then verify that it is part of this module.
    2. If 'livechat-widget' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Screenshots**
![image](https://user-images.githubusercontent.com/49153978/152295753-c95275ed-8719-4bdf-8879-a795ef3758b3.png)

**Version:**
 -Angular Version 9

**Comment by walaszczykm** [comment]
Hello @AmolShinde11 👋 

Sad to hear that you have encountered an error with our package.
Unfortunately, as for now, this package is aimed to support the last two Angular versions: 12 and 13 as below 12 the output produced by`@angular/compiler@13` seems to be incompatible with the lower version.

The dependence on specific Angular version is emphasized using `peerDependecies` inside packages `package.json` as you can see here: https://github.com/livechat/chat-widget-adapters/blob/832c5cafc34c48950ef1112c9c9b2f335f340558/packages/widget-angular/package.json#L33

Because your request targets a version lower than the currently supported ones, this issue will not have a high priority. I won't close it right away and I will try to do some debugging first and we will see if we can do anything more to actually support a wider range of Angular versions.

Feel free to propose your solution if you will have one or provide any more details if some will be available 🙂

**Comment by walaszczykm** [comment]
Closing as for now we are not officially supporting the Angular versions lower than 12.
The issue will be reopened If we will introduce support for Angular 11.
