### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by syn6UK** [livechat/chat-widget-adapters#29]
I am trying to figure out how on earth to programatically trigger the window to open from a button click. We are using React with next.js and the livehcat component is being rendered in the app,.tsx file, but how do you access the methods on that widget? Your documentation gives no clues to this.

**Comment by walaszczykm** [comment]
Hello @syn6UK 👋 

Please **use provided issue templates** and do not skip the proposed structure. They are defined for the purpose to point what information we need in order to properly take care of your request. Link for reference: [Feature request](https://github.com/livechat/chat-widget-adapters/issues/new?assignees=walaszczykm&labels=enhancement&template=feature_request.md&title=).

Answering your question. The [documentation](https://github.com/livechat/chat-widget-adapters/blob/master/packages/widget-react/README.md) for `@livechat/widget-react` package directly explains how the `LiveChatWidget` should be used inside `React` application. 

The main goal of the Chat Widget Adapters project is to provide a framework-aware implementation for using our Chat Widget without the need to directly access our [JS API](https://developers.livechat.com/docs/extending-chat-widget/javascript-api). But the JS API is an option that is always available to you if you wish to integrate the widget that way.

Being a framework-aware implementation each adapter integrates the Chat Widget with a framework-specific reactivity model and best practices. In the case of React, we expose the component `LiveChatWidget` which accepts a set of props described in the documentation: [README.md#props](https://github.com/livechat/chat-widget-adapters/blob/master/packages/widget-react/README.md#props). Props are split into two categories: Configuration and Event handlers. 

Using React's definition/approach to how the UI should be rendered it's most commonly represented as: The UI is a result of component function being called with passed properties. That way we should always render Chat Widget in the same state while the same properties are provided. All of the props available on `LiveChatWidget` component are properly reactive and you can steer the behavior of the widget by simply changing their values, the same way as you do with many other React components.

An example implementation of controlled widget visibility comes down to the concept of [Controlled Component](https://reactjs.org/docs/forms.html#controlled-components) documented directly on official React docs. Properties of `LiveChatComponent` being used are also described in the project's documentation: `visibility`, `onVisibilityChanged`.

```ts
import * as React from 'react'
import { LiveChatWidget } from '@livechat/widget-react'
import type { WidgetState, EventHandlerPayload } from '@livechat/widget-react'

function App() {
  const [visibility, setVisibility] = React.useState<WidgetState['visibility']>('minimized')

  function handleSelectChange(event: React.ChangeEvent<HTMLSelectElement>) {
    setVisibility(event.target.value as WidgetState['visibility'])
  }

  function handleVisibilityChanged({ visibility }: EventHandlerPayload<'onVisibilityChanged'>) {
    setVisibility(visibility)
  }

  return (
    <main>
      <div style={{ color: 'white' }}>
        <label htmlFor="visibility">Widget visibility: </label>
        <select id="visibility" value={visibility} onChange={handleSelectChange}>
          <option>minimized</option>
          <option>maximized</option>
          <option>hidden</option>
        </select>
      </div>
      <LiveChatWidget license="12332502" visibility={visibility} onVisibilityChanged={handleVisibilityChanged} />
    </main>
  )
}
```

Here is a video showcasing the example:

https://user-images.githubusercontent.com/9700566/154242207-36df161c-239c-4dab-a4f0-9238ff99f1e0.mov
