### ISSUE TITLE
Widget simply doesn't work

### ISSUE THREAD

**Issue by syn6UK** [livechat/chat-widget-adapters#30]
"Can't perform a React state update on an unmounted component." Appears in the console log, and the app memory leaks and crashes my browser.

Simply following your code example in next.js caused this. Your older deprecated widget works.

**Comment by walaszczykm** [comment]
Hello @syn6UK 👋 

It's sad to hear you have encountered such an issue in your application. We have tested the `@livechat/widget-react` package together with Next.js in basic setup and it works correctly.

In order to provide any further help we would need more information about your setup, used versions steps to reproduce alongside some code samples how you are using the LiveChatWidget component in your application. Additionally, it would be helpful to know if you have used any of provided React Hooks.

Please use provided issue templates and do not skip the proposed structure. They are defined for the purpose to point what information we need in order to properly take care of your request. Link for reference: [Bug report](https://github.com/livechat/chat-widget-adapters/issues/new?assignees=walaszczykm&labels=bug&template=bug_report.md&title=).
