### ISSUE TITLE
Can't use avatar button in react

### ISSUE THREAD

**Issue by Aryan-mor** [livechat/chat-widget-adapters#35]
I implement library to my project but have some problem.

`        <LiveChatWidget
            license="*****"
            visibility="minimized"
        />
`
But is show in my code like this =>
![image](https://user-images.githubusercontent.com/22844436/156138677-d891a4b0-1d70-48ce-9b43-f864269a4d75.png)

I need change to like this =>
![image](https://user-images.githubusercontent.com/22844436/156138840-6e98721d-4435-4127-b1e7-7b791d6ef73e.png)

**Comment by walaszczykm** [comment]
Hello @Aryan-mor 👋 

In order to change the appearance of the minimized Chat Widget and also overall adjust the look and feel of it, you need to configure it on your LiveChat account 🙂 

This project allows you to seamlessly integrate the LiveChat Chat Widget into your project but its configuration and setup are still done as always inside LiveChat Agent App after signing into your account.

You can read more about it here: https://www.livechat.com/help/customize-your-chat/#appearance
