### ISSUE TITLE
Question: How to use with Custom Identity Provider?

### ISSUE THREAD

**Issue by mrsamse** [livechat/chat-widget-adapters#58]
I would like to use the react implementation of this widget, but I'm not sure how it works with a Custom Identity Provider. As far as I see, I don't have access to the `custom_identity_provider` object which is shown in the documentation: https://developers.livechat.com/docs/extending-chat-widget/custom-identity-provider

**Comment by walaszczykm** [comment]
Hello, @mrsamse 👋 thanks for reporting the issue. 

You are right, the LiveChat Chat Widget supports an advanced feature called Custom Identity Provider. Still, at the moment, Chat Widget Adapters does not expose a way to pass such provider via props into `LiveChatWidget` component (regardless of the chosen framework).

It's a good topic for enhancement in the package 👌 Because of that, I have changed the label from "bug" to "enhancement", as your issues do not relate to any miss functionalities of currently supported features. 

We will plan to add the support for passing Custom Identity Provider to the Chat Widget instantiated via adapters 👍 We will use this issue to drop further updates how it's going so stay tuned 😉
